env:
  - TRAVIS=true
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
script:
  - COVERAGE=true bundle exec rspec spec
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: rbx-19mode
